linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 60
    statements: 45
  goconst:
    min-len: 4
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
  gocyclo:
    min-complexity: 20
  mnd:
    settings:
      mnd:
        checks: argument,case,condition,return
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 250
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: false
    require-specific: true
  exhaustive:
    default-signifies-exhaustive: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - copyloopvar
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    # Ignore magic numbers, inline strings and function length in tests
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - funlen
    # Ignore line length for string assignments
    - linters:
        - lll
      source: "^(.*= (\".*\"|`.*`))$"
    # Ignore unnecessary defer warnings
    - linters:
        - gocritic
      text: "unnecessaryDefer:" 